### ISSUE TITLE
Convert to Spark

### ISSUE THREAD

**Issue by philsturgeon** [patrickpopowicz/codeigniter-bitly#1]
Hey patrickpopowicz, 

Can you make this into a [Spark](http://getsparks.org/make-sparks)? It would make it much easier to find between many many broken libraries.

For an example look at how codeigniter-curl looks:

https://github.com/philsturgeon/codeigniter-curl

The README.md helps people work out whats going on, and the autoload is run by the Sparks code to load libraries and config as soon as the spark is loaded.

The spark.info is used by their end to work out if things are compatible. also, can you rename this to "codeigniter-bitly" to be more standard?

Thanks :)

**Comment by patrickpopowicz** [comment]
I've been meaning to convert this over to a spark for a while now. Will do so as soon as I get an opportunity.

**Comment by patrickpopowicz** [comment]
Finally got around to converting this over into a spark. Thanks for originally bringing it to my attention.
