### ISSUE TITLE
Passing bit.ly url to twitter

### ISSUE THREAD

**Issue by subdesign** [patrickpopowicz/codeigniter-bitly#2]
Hi, I don't know if its the libs problem or not, but when I try to pass a shortened url, no link appears in the tweet window. But when I hover over the tweet button, the shortened bitly url is there, but with - i guess - strange charaters. Any idea or hint why I have this prob. I use javascript twitter button, and the tweet process works if i don't shorten the link I want to share. Thank you.
Example: http://goo.gl/VZ6b9

**Comment by patrickpopowicz** [comment]
When you just use the library are you getting back a link that works correctly?

**Comment by subdesign** [comment]
Yes! As I see now I have a %0A always after the short url, surely thats why I have this problem. So googling.. Thanks, great lib!

EDIT: Solved. A php trim function removed the line feed char.
